# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

matrix:
  include:
  - r: devel
    os: linux
  - r: devel
    os: osx

  - r: release
    os: linux
    after_success:
    - Rscript -e 'covr::codecov()'
  - r: release
    os: osx

  - r: oldrel
    os: linux
  - r: oldrel
    os: osx

  - r: 3.3
    os: linux
  - r: 3.3
    os: osx

  - r: 3.2
    os: linux
  - r: 3.2
    os: osx

  - r: 3.1
    os: linux
  - r: 3.1
    os: osx
